export const HANDLE_ADD_ROW = "HANDLE_ADD_ROW";
export const HANDLE_TOGGLE_SALES_FIELD_STATUS = "HANDLE_TOGGLE_SALES_FIELD_STATUS";
export const HANDLE_TOGGLE_CALLHUB_FIELD_STATUS = "HANDLE_TOGGLE_CALLHUB_FIELD_STATUS";

export const HANDLE_TOGGLE_FIELDS_STATUS = "HANDLE_TOGGLE_FIELDS_STATUS";

export const HANDLE_KEYS = "HANDLE_KEYS";
export const HANDLE_VALUES = "HANDLE_VALUES";

export const HANDLE_DELETE = "HANDLE_DELETE";

export const HANDLE_UPDATE_FINAL_DATA = "HANDLE_UPDATE_FINAL_DATA";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";

export const RESET_FINAL_DATA = "RESET_FINAL_DATA"